# Generated by Django 4.0.3 on 2022-04-29 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='users_ids',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
