# Generated by Django 4.0.3 on 2022-03-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientsession',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
