# Generated by Django 4.0.3 on 2022-03-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_notification_options_notification_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('client__id', 'id')},
        ),
    ]
